export type ProductType = {
  id: string;
  user_id: string;
  name: string;
  sku: string;
  ncm: string;
  observations?: string;
  unit_price: number;
  price_today: number;
  price_in_2026?: number;
  price_in_2027?: number;
  shipping: number;
  fix_post: number;
  others_post: number;
  icms: number;
  icms_st: number;
  ipi: number;
  pis_cofins: number;
  others: number;
  profit: number;
  sales_icms?: number;
  sales_pis_cofins?: number;
  created_at: string;
  updated_at: string;
  updated_by?: string;
};
